// src/components/DirectMessages/Chats.svelte
<script>
	import { chatContacts, selectedChat } from '$lib/globals/SocialData';
	import { onMount } from 'svelte';
	import { backendURL } from '../../utils/constants';
	import ProfileIcon from '../Profile/ProfileIcon.svelte';
	import { isSuccess } from '../../utils/status';
	import { goto } from '$app/navigation';
	import { getRequest, postRequest } from '../../utils/fetchers';

	let loading = $state(true);

	async function fetchSocialData() {
		let res = await getRequest('/chat/list');

		let data = await res.json();

		$chatContacts = data.content;
		// console.log($chatContacts);

		loading = false;
	}

	onMount(fetchSocialData);

	async function navigateToChat(id) {
		let res = await postRequest('/chat/', { targetUser: { id: id } });

		let data = await res.json();
		if (isSuccess(data.status)) {
			goto(`/app/chat/${data.content.id}`);
		}
	}
</script>

{#if !loading}
	{#if $chatContacts.length >= 1}
		{#each $chatContacts as chatContact}
			{@render Contact(chatContact, chatContact.participants[0].user)}
		{/each}
	{:else}
		<div class="flex h-full w-full flex-col items-center justify-center">
			<p class="text-shade-600 text-center text-lg font-semibold">It's so quiet here…</p>
			<p class="text-shade-600 text-center">Break the silence and chat!</p>
		</div>
	{/if}
{:else}
	<div class="flex h-full w-full flex-col items-center justify-center">
		<div class="loader"></div>
	</div>
{/if}

{#snippet Contact(chat, user)}
	<button
		class={`hover:bg-shade-700 ${$selectedChat == chat.id ? 'bg-shade-750' : ''} flex w-[97%] cursor-pointer items-center gap-3.5 rounded-md p-2 transition-all duration-300`}
		onclick={() => navigateToChat(user.id)}
	>
		<div class="h-[35px] w-[35px]">
			<ProfileIcon statusIndicator={true} />
		</div>
		<div class="flex flex-col items-start">
			<p class="text-shade-600 text-sm">{user.displayName}</p>
			<!-- <p class="text-shade-600 text-xs">{username}</p> -->
		</div>
	</button>
{/snippet}

// app/components/side menus/DirectMessages/Chats.jsx
"use client";
import React, { useEffect, useState } from "react";
import Contact from "../Contact";
import { getRequest } from "@/app/utils/fetchers";
import LoadingSpinner from "../../Icons";
import { useSocket } from "../../SocketProvider";

function Chats() {
  const [chats, setChats] = useState([]);
  const [loading, setLoading] = useState(true);

  const [activeChatId, setActiveChatId] = useState();

  const socket = useSocket();

  useEffect(() => {
    if (!socket) return;

    const handleUpdateChatData = (message) => {
      setChats(message.chatList || []);
    };

    socket.on("update-chat-list", handleUpdateChatData);

    return () => {
      socket.off("update-chat-list", handleUpdateChatData);
    };
  }, [socket]);

  useEffect(() => {
    fetchChats();
  }, []);

  if (chats.length === 0 && loading) return <LoadingWrapper />;
  else if (chats.length >= 1)
    return chats.map((chat, index) => (
      <Contact
        user={chat.participants[0].user}
        key={index}
        chat={chat}
        activeChatId={activeChatId}
        setActiveChatId={setActiveChatId}
      />
    ));
  else return <NoChatsNotation />;

  function LoadingWrapper() {
    return (
      <div className="flex h-full flex-col gap-2">
        <div className="flex h-full w-full items-center justify-center">
          <div className="text-shade-600 w-6 h-6">
            <LoadingSpinner />
          </div>
        </div>
      </div>
    );
  }

  function NoChatsNotation() {
    return (
      <div className="flex h-full flex-col gap-2">
        <div className="flex h-full w-full flex-col items-center justify-center">
          <p className="text-shade-600 text-center text-lg font-semibold">
            It's so quiet here…
          </p>
          <p className="text-shade-600 text-center">
            Break the silence and chat!
          </p>
        </div>
      </div>
    );
  }

  async function fetchChats() {
    try {
      const res = await getRequest("/chat/list");
      const data = await res.json();

      setChats(Array.isArray(data.content) ? data.content : []);
      setLoading(false);
    } catch (error) {
      console.error("Failed to fetch chats:", error);
      setChats([]);
    }
  }
}

export default Chats;
